<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-JGMGK3K" failures="0" tests="3" name="org.rahulshettyacademy.eCommersetc_2" time="0.010" errors="1" timestamp="11 May 2024 12:56:31 GMT" skipped="2">
  <testcase classname="org.rahulshettyacademy.eCommersetc_2" name="configureAppium" time="0.010">
    <error message="Error at index 1 in: &quot;1:4723&quot;" type="java.net.MalformedURLException">
      <![CDATA[java.net.MalformedURLException: Error at index 1 in: "1:4723"
at java.base/java.net.URL.<init>(URL.java:708)
at java.base/java.net.URL.<init>(URL.java:569)
at java.base/java.net.URL.<init>(URL.java:516)
at io.appium.java_client.service.local.AppiumDriverLocalService.<init>(AppiumDriverLocalService.java:84)
at io.appium.java_client.service.local.AppiumServiceBuilder.createDriverService(AppiumServiceBuilder.java:473)
at io.appium.java_client.service.local.AppiumServiceBuilder.createDriverService(AppiumServiceBuilder.java:57)
at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:498)
at com.rahulsheetyacademy.utils.AppiumUtils.startAppiumServer(AppiumUtils.java:56)
at org.rahulshettyacademy.TestUtils.AndroidBaseTest.configureAppium(AndroidBaseTest.java:53)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.NumberFormatException: Error at index 1 in: "1:4723"
at java.base/java.lang.NumberFormatException.forCharSequence(NumberFormatException.java:83)
at java.base/java.lang.Integer.parseInt(Integer.java:751)
at java.base/java.net.URLStreamHandler.parseURL(URLStreamHandler.java:237)
at java.base/java.net.URL.<init>(URL.java:703)
... 34 more
]]>
    </error>
  </testcase> <!-- configureAppium -->
  <testcase classname="org.rahulshettyacademy.eCommersetc_2" name="fillFormPositiveFlow" time="0.000">
    <skipped/>
  </testcase> <!-- fillFormPositiveFlow -->
  <testcase classname="org.rahulshettyacademy.eCommersetc_2" name="fillFormErrorValidation" time="0.000">
    <skipped/>
  </testcase> <!-- fillFormErrorValidation -->
</testsuite> <!-- org.rahulshettyacademy.eCommersetc_2 -->
